language: php

php:
  - 5.4
  - 5.5
  - hhvm

before_script:
    - composer self-update
    - composer install --dev

script:
    - phpunit --coverage-clover=coverage.clover
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
