#!/usr/bin/env php
<?php

require_once __DIR__ . DIRECTORY_SEPARATOR . 'Bootstrap.php';

use Gerrie\Command\CreateDatabaseCommand;
use Gerrie\Command\CrawlCommand;
use Symfony\Component\Console\Application;

$application = new Application('Gerrie', '0.2.0-dev');
$application->add(new CreateDatabaseCommand());
$application->add(new CrawlCommand());
$application->run();